### ISSUE TITLE
Adding / modifying Product Type tags

### ISSUE THREAD

**Issue by jerikac** [US-GHG-Center/veda-config-ghg#146]
Feedback from our demo on 9/21 -- include the Product Type tag in the dataset card (rather than, or before the topic tag?). 

Also requested to change the tags “Ground Data” & “Satellite Data” to "Ground **Measurements**", "Satellite **Measurements**"
and add the following tags to Product Type:

- "Gridded Inventory" (applicable to EPA Methane and ODIAC datasets)
- "Merged" (for datasets that are composed of both Measurements and Model Outputs)

**Comment by jerikac** [comment]
@slesaad Are you working on this?

**Comment by slesaad** [comment]
I can change the tags, but we can't do this part
> include the Product Type tag in the dataset card (rather than, or before the topic tag?)

**Comment by jerikac** [comment]
That's alright, it's higher priority to have the tags changed, and new tags added (Merged and Gridded Inventory Data). The Gridded Inventory Data tag applies to EPA Methane and ODIAC Data. Thanks for looking into this!!

**Comment by slesaad** [comment]
renamed the tags, not doing anything about merged right now
