### ISSUE TITLE
[Design] Make embedded visualization interfaces feel more official

### ISSUE THREAD

**Issue by j08lue** [US-GHG-Center/veda-config-ghg#206]
There is a very simple concern for the GHG Center web presence: Since it is to be an authoritative, reliable, reviewed and vetted source of information, all the content and tools we present should look and feel authoritative.

Currently, the embedded apps do not feel like that - mostly because of their external URLs (GitHub pages in the `nasa-impact` org).

We discussed different fixes for that:

- https://github.com/NASA-IMPACT/veda-config-ghg/issues/199

With the conclusion to keep the apps hosted elsewhere, but prettify the URLs through CloudFront so they give the impression of being an authoritative part of the GHG Center web presence.

## Success criteria

- [ ] Moved apps to be embedded into the [US GHG Center GitHub org](https://github.com/US-GHG-Center) and
- [ ] Prettified the URLs through CloudFront (ghg.center something)

**Comment by j08lue** [comment]
Perhaps also call the interfaces for the NOAA Global Monitoring Laboratory datasets something more spelled out than `noaa-viz`, pls.

**Comment by aboydnw** [comment]
@slesaad I am curious what you think about the status of this ticket, especially with R3 almost done. Should we keep it open or do you think it's been addressed?

**Comment by slesaad** [comment]
yes this can be closed
