### ISSUE TITLE
Review which datasets should be available in new E&A interface

### ISSUE THREAD

**Issue by j08lue** [US-GHG-Center/veda-config-ghg#261]
The current Exploration & Analysis interface [tests](https://github.com/NASA-IMPACT/veda-config-ghg/pull/217) revealed that some datasets have an Explore button in the Data Catalog / Dataset page but should in fact be omitted from exploration in that interface because it is not well suited for that particular dataset. Main case is `epa-ch4emission-yeargrid-v2express`, but there may be more datasets that are either technically not suited for E&A-style browsing or the data providers expressed that this interface is not adequate.

Clicking that Explore button now (e.g. in [this feature preview](https://deploy-preview-217--ghg-demo.netlify.app/data-catalog/epa-ch4emission-yeargrid-v2express)) shows up the pre-filtered data layer selection, but no layers are available (since they are omitted):

![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/3404817/ad46fc63-a408-4673-98ba-c5e8fca14731)

We need to ultimately figure out how to offer users adequate ways to browse these datasets. In the meantime, we should make sure this Explore option does not show up on the Dataset page if the dataset is configured to be omitted from E&A.
 
## Acceptance criteria

- [x] Prepared a list of datasets that should be omitted from E&A exploration
- [x] https://github.com/NASA-IMPACT/veda-ui/issues/796

**Comment by j08lue** [comment]
Pinging @deborahUAH for completing the list of datasets to omit from E&A exploration.

**Comment by deborahUAH** [comment]
@siddharth0248  provided a dataset matrix created with the help of Emily and Lesley (GSFC).  @siddharth0248 provide link in this ticket please.  We need to look at individual dataset layers, not just datasets as a whole next.

**Comment by j08lue** [comment]
This is the matrix:
https://docs.google.com/spreadsheets/d/1Yegj1ZGbx-Bah1HEFl-fgEPDyTJ5jYewT_1n51eFAEQ/edit#gid=0

**Comment by j08lue** [comment]
We did not implement the full combination matrix but a way to exclude EPA Gridded Inventory from being compared with other datasets.
