### ISSUE TITLE
Trailing slashes

### ISSUE THREAD

**Issue by aboydnw** [US-GHG-Center/veda-config-ghg#262]
Looking at google analytics data, there seems to be multiple entries for essentially the same URL, just with a trailing slash.
![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/92742765/b1c4122a-c75d-400b-8309-fff525f32385)

Is it possible to set a rule across the app that redirects people to either a url with the trailing slash or one without? That would help analytics be consistent

**Comment by aboydnw** [comment]
@j08lue @hanbyul-here @sandrahoang686 fyi on this ticket, I'll leave you all to prioritize. Deborah asked about it when I was looking over the analytics with her last week. I did some digging and all the google analytics forums suggest to fix the root cause in the app rather than do some wizardry in google analytics to hide it. There aren't many good options in GA4

**Comment by hanbyul-here** [comment]
I feel like there will be a more elegant solution using Cloudfront rather than redirecting every page on the front-end side. @amarouane-ABDELHAK any thought?

**Comment by aboydnw** [comment]
Closing, we have found some workarounds on the analytics side
