### ISSUE TITLE
GHGC Site Bug Report: EMIT Data Visualization

### ISSUE THREAD

**Issue by fb0023** [US-GHG-Center/veda-config-ghg#273]
We have received a bug report regarding the EMIT data visualization on the embedded GHGC page. The feedback was submitted by Brian and a copy of his feedback has been transcribed below for your reference.

**Brian’s feedback:**
“When i'm in the embedded page for EMIT data visualization if i click with two fingers on the trackpad and separate them the view of the globe changes (i.e. from top down to side view). I'm using a mac and my colleague on a windows machine was unable to recreate the issue.”

**Brian attached the following video:**
https://github.com/NASA-IMPACT/veda-config-ghg/assets/142605787/ed1b005d-c441-4f0c-a8ae-3d3ad7b13cea

**GHG Center Help Desk Ticket ID:** https://github.com/NASA-IMPACT/us-ghg-center-feedback/issues/54

**Comment by amarouane-ABDELHAK** [comment]
This is resolved
