### ISSUE TITLE
[Design] Homepage Refresh

### ISSUE THREAD

**Issue by faustoperez** [US-GHG-Center/veda-config-ghg#307]
### Description

We have been asked to update the design of the welcome page to include more statistics and facts. This enhancement aims to boost credibility and engage our audience by emphasizing that the US GHG Center is a prime source of factual information.

Additionally, there is a suggestion to refine the user interface (UI) to prioritize interactive elements, such as big numbers and charts, over the current text-heavy layout. This approach is intended to make the experience more dynamic and engaging for our audience. [nor-discover.org](https://nor-discover.org/) is one example that was provided by stakeholders as having this large graphic/visual style.

A potential hierarchy of information on the homepage could be:

- Spinning globe (assuming GHG stakeholders want to keep this, but based on direction above about large graphics, maybe that is flexible)
- GHG metrics (see slide 2 of [this deck](https://drive.google.com/file/d/1iOo6Wf0O9jsNFb67xK3BAfntn2bk69ru/view)) pulled from [this api](https://climate.nasa.gov/api/v1/vital_signs/)
- Urban content carousel
- Some calls to action like 'Tour the GHG Center' or 'Browse the Stories'
- Links to 'workflows' for scientists and decision makers

### Acceptance criteria

- [ ] [Potentially] meet with key GHG stakeholders (Deborah, Kelsey, others) to brainstorm/receive direction
- [ ] Designs shared and reviewed with GHG team and stakeholders

**Comment by adykrni** [comment]
hey, is this task still open? I would like to. contribute to this :)

**Comment by j08lue** [comment]
@adykrni, we are looking for project-internal design guidance and this work will happen within our existing team. But if you feel inspired, please feel free to post some visual tokens of what you would suggest. We will not have resources to coach you much, though. If you are looking to contribute to this project, please check out tickets labelled [good first issue](https://github.com/US-GHG-Center/veda-config-ghg/labels/good%20first%20issue).

**Comment by j08lue** [comment]
A great reference for a multi-ausdience, fact-driven website that @deborahUAH shared today: https://nasalifelines.org/

**Comment by j08lue** [comment]
### https://carbonplan.org

![image](https://github.com/US-GHG-Center/veda-config-ghg/assets/3404817/a9da31ab-c74b-4792-8e60-d023f59d3310)

### https://climatetrace.org

![image](https://github.com/US-GHG-Center/veda-config-ghg/assets/3404817/442d54fd-c36d-46e8-b22d-dc0cf67282b8)

**Comment by aboydnw** [comment]
@Jeanne-le-Roux @deborahUAH @jerikac I'd like to start the conversation on the home page here. Do we know more about what information to show on the homepage as part of R3? Or any specific goals for R3 (like improving decision maker usage) that should be considered on this home page?

If you have statistics, content, and/or ideas for functionality then Fausto and team can take that and come up with a concept for the home page

**Comment by deborahUAH** [comment]
I've asked @siddharth0248  to put together a document of examples and what is good on each as well as some indications of what we don't want. He can link it here or add the content directly here.  in the meantime, I will add a list of stats ideas and other thoughts.

**Comment by faustoperez** [comment]
Some more links and resources related to this ticket:

- **Earth HQ:** https://earthhq.org/
- **Climate Watch:** https://www.climatewatchdata.org/ghg-emissions?end_year=2021&start_year=1990

**Comment by aboydnw** [comment]
@faustoperez I just edited the details in this ticket, let's discuss during sprint planning

**Comment by aboydnw** [comment]
Update from the meeting today with Kelsey and GHG team:

- The biggest update to the homepage for R3 is to add the carousel. We are tracking this in https://github.com/NASA-IMPACT/veda-ui/issues/1098
- There might be some light content updates, as well as moving some of the existing content around topic areas to the new "Topics" page
- There won't be any major additions or stylistic changes to the homepage, although it should become much simpler with less content
- We can probably remove the link directly to the Data Catalog
- We are not going to insert any links directly to a Decision Maker workflow or Scientist workflow for this release, although we should continue those discussions in the future.

**Comment by aboydnw** [comment]
Given that, then @faustoperez @Jeanne-le-Roux I wonder if we should close this ticket out, and track carousel development in the other ticket?

**Comment by Jeanne-le-Roux** [comment]
@aboydnw I'm fine with closing this out. I see your ticket licked above for the carousel implementation - I've created [this ticket](https://github.com/US-GHG-Center/ghgc-architecture/issues/325) to track the detailed content updates.
