### ISSUE TITLE
Add accessibility link in the footer

### ISSUE THREAD

**Issue by slesaad** [US-GHG-Center/veda-config-ghg#323]
# Description
A footer link needs to be added to the website which links to NASA's accessibility statement, located at https://www.nasa.gov/accessibility/. Due by March 20, 2024

# Context
>MESSAGE TO ALL NASA EMPLOYEES FROM THE CHIEF INFORMATION OFFICER
Point of Contact: Courtney Ritz, IT Accessibility Lead, 301-286-7946, courtney.l.ritz@nasa.gov
----------------------------------------------------------
>Section 508 Compliance and Digital Accessibility
>NASA is committed to creating a better digital experience for people with disabilities. OMB recently released M-24-08, Strengthening Digital Accessibility and the Management of Section 508 of the Rehabilitation Act. This memo reinforces the importance of cultivating a positive culture of digital accessibility and assigns immediate action to those managing NASA's digital content.
>By March 20, 2024, website owners must verify that their websites link to NASA's accessibility statement, located at https://www.nasa.gov/accessibility/. This link is required to appear in the footer of all of NASA's web sites, both external and internal.  As this is not a new requirement, most websites should already be linking to this statement. 
For guidance on how to meet this requirement and validate your link to NASA's Accessibility Statement, please visit OMB Guidance on Accessibility Statements on Web Sites. 
In the months to come, we will be rolling out more agency-wide guidance, training, and tooling to empower everyone at NASA to contribute to our culture of digital accessibility. Visit our Section 508 intranet site for links to the latest resources.
For questions about OMB M-24-08 or other accessibility topics, please contact Courtney Ritz, the Agency IT Accessibility Lead, via e-mail at courtney.l.ritz@nasa.gov or by phone at 301-286-7946. A copy of this memo may be found on the OCIO website.
Jeff Seaton

# AC
- [ ] A footer link called "Accessibility" added to the website

**Comment by slesaad** [comment]
@faustoperez Need some design guidance on where this accessibility link should go. We could add it to the row of links in the footer on the left. However, it seems out of place with all those other links that are more or less directly related to the GHG Center. 

![image](https://github.com/US-GHG-Center/veda-config-ghg/assets/7830949/a2e1fb40-27a1-4463-b8a5-b4819f542e83)

cc @j08lue @sandrahoang686 @hanbyul-here

**Comment by j08lue** [comment]
I wonder who this link is meant for. 

I guess us, actually - we do not only need to add the link but also review the accessibility standards NASA commits to and make sure we comply.

If it is for users - _As a user who depends on improved accessibility for websites, I would like to know whether the site I am viewing is committed to fulfilling NASA standards, and know who I can contact if I find that it does not fulfill my needs._

I'd put it next to (underneath) the name of the responsible official or so and call it "Our Commitment to Accessibility".

My 2ct

**Comment by faustoperez** [comment]
> @faustoperez Need some design guidance on where this accessibility link should go

Thank you @slesaad , I am assigning this to myself and will come back with a design in the next few days 👍

**Comment by faustoperez** [comment]
Created the links for both desktop and mobile. Checked accessibility contrast with the footer bg color, it passes WCAG AAA: https://webaim.org/resources/contrastchecker/?fcolor=1048AA&bcolor=F5F5F6

Link to Figma file 👉 https://www.figma.com/file/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?type=design&node-id=1194%3A6485&mode=design&t=r614lc2aGjKASSI2-1

<img width="3580" alt="Accessibility link in the footer" src="https://github.com/US-GHG-Center/veda-config-ghg/assets/12268629/cde203e1-3d17-4648-9aaf-e41d5d724284">

**Comment by slesaad** [comment]
thanks @faustoperez!
