### ISSUE TITLE
Relative links in MDX?

### ISSUE THREAD

**Issue by j08lue** [US-GHG-Center/veda-config-ghg#361]
We have a link in this page: https://staging.earth.gov/ghgcenter/data-catalog/epa-ch4emission-yeargrid-v2express

Where we have hard-coded the hostname (https://earth.gov):

https://github.com/US-GHG-Center/veda-config-ghg/blob/535e8ac303d458c555c2775d03b9ea4b9a92adc0/datasets/epa-ch4emission-yeargrid-v2express.data.mdx?plain=1#L2643

![image](https://github.com/US-GHG-Center/veda-config-ghg/assets/3404817/737409ce-4e58-41e6-8b7c-30a08af0affe)

This means that on the **staging** version (https://staging.earth.gov/ghgcenter/data-catalog/epa-ch4emission-yeargrid-v2express), this link still points to the production version and same for the previews (https://ghg-demo.netlify.app).

## Acceptance criteria

- [x] If possible, changed the link to a relative one, such that it points to the staging target when deployed in staging

**Comment by siddharth0248** [comment]
PR : https://github.com/US-GHG-Center/veda-config-ghg/pull/383

**Comment by siddharth0248** [comment]
In current demo preview /ghgcenter/exploration?search=epa-ch4emission-yeargrid-v2express&datasets=%5B%5D won't work. It should be **/exploration?search=epa-ch4emission-yeargrid-v2express&datasets=%5B%5D**

But for earth.gov relative link needs to have ghgcenter

**Comment by j08lue** [comment]
Yes, seems like there is a reason why these are absolute links, so not just something to fix in the content. Let's keep this open for now and see when the UI team can look into it.

**Comment by j08lue** [comment]
Ah, I see @hanbyul-here is already getting involved. 😄 

> I thought <Link> component handles this problem already

👌
