### ISSUE TITLE
Configure EMIT/AVIRIS-3 data insight in the dashboard

### ISSUE THREAD

**Issue by slesaad** [US-GHG-Center/veda-config-ghg#380]
# Description
Follow up on https://github.com/US-GHG-Center/ghgc-architecture/issues/115

The [EMIT/AVIRIS-2 data insight](https://docs.google.com/document/d/1r1RW7l2aO0-4ImnWacx45we0izxpELLgGDTFVFP_JNA/edit?usp=sharing) is approved and ready to be published.
It needs to be configured in the dashboard.

# AC
- [x] A PR to veda-config-ghg with the new data insight based on the google docs

**Comment by Jeanne-le-Roux** [comment]
Preview: https://deploy-preview-384--ghg-demo.netlify.app/stories/emit-and-aviris-3

Also adding a note that we'll have to add a link to the data insight to the [EMIT overview page](https://docs.google.com/document/d/1hPvwDI4-kAObxNfdWuiivdZcgTbJYN536ThwIIveL7o/edit#heading=h.g5xc8g7us147) (Learn More section)

**Comment by jerikac** [comment]
Deborah reviewing Shanna's comments/changes. expect to be delivered for TEG review today (5/28). Unsure of TEG review timeline.

**Comment by Jeanne-le-Roux** [comment]
Waiting for Aries feedback - @deborahUAH will notify us when the final draft is ready to be implemented.

**Comment by deborahUAH** [comment]
Final changes to text underway. I expect the changes to arrive for Thursday 6/20. Please be ready to implement the changes so we can push on Monday.

**Comment by Jeanne-le-Roux** [comment]
The data insight has been published: https://earth.gov/ghgcenter/stories/emit-and-aviris-3
