### ISSUE TITLE
Push a new release by Wednesday

### ISSUE THREAD

**Issue by slesaad** [US-GHG-Center/veda-config-ghg#382]
# Description
Post release 2, there are still some known issues that we couldn't push for release 2.
- Delete button not working for preset AOIs  - https://github.com/NASA-IMPACT/veda-ui/pull/945
- Preset AOIs not working - https://github.com/NASA-IMPACT/veda-ui/pull/941

~~Also, there's a new data insight that has been approved and needs to be pushed.~~
~~- https://github.com/US-GHG-Center/veda-config-ghg/issues/380~~

We want to do both by Wednesday before the next newsletter goes out.

# AC
- [x] New release pushed with fixes + ~~new data insight~~ by Wednesday

**Comment by Jeanne-le-Roux** [comment]
Also: https://github.com/US-GHG-Center/ghgc-architecture/issues/226

**Comment by slesaad** [comment]
V2.0.1 released! 
https://github.com/US-GHG-Center/veda-config-ghg/releases/tag/v2.0.1
