### ISSUE TITLE
Create a comprehensive list of things to test before a release

### ISSUE THREAD

**Issue by slesaad** [US-GHG-Center/veda-config-ghg#398]
# Description

A recent release introduced a bug in the dashboard - see more in [this slack thread](https://teamdsig.slack.com/archives/C054MDFFCKV/p1717019700297849). This could have been avoided if we'd tested the dashboard thoroughly. 

We should create a comprehensive list of things to be tested before making a new release. Things like:
1. Layer visualization load in the map explorer
2. Data comparison between layers works
3. Date navigation works as expected
4. ...

This will also be useful for when we want to add automated tests to the frontend.

# Acceptance Criteria
- [x] A comprehensive testing document

**Comment by Jeanne-le-Roux** [comment]
[QA checklist document](https://docs.google.com/document/d/1k8jQh5cuadwdWS5FEILo28cpkmhyKHLCNWXw2ETPilo/edit)
