### ISSUE TITLE
Selected AOIs do not persist when E&A URL is shared

### ISSUE THREAD

**Issue by sanzog03** [US-GHG-Center/veda-config-ghg#406]
Generally, In exploration the "delete all areas" button work when there are multiple polygons, i.e. without selecting any polygons. However, for the [link](https://staging.earth.gov/ghgcenter/exploration?datasets=%5B%7B%22id%22%3A%22post-wetland-id%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%2C%7B%22id%22%3A%22min%22%2C%22label%22%3A%22Min%22%2C%22chartLabel%22%3A%22Min%22%2C%22themeColor%22%3A%22infographicA%22%2C%22style%22%3A%7B%22strokeDasharray%22%3A%222+2%22%7D%7D%2C%7B%22id%22%3A%22max%22%2C%22label%22%3A%22Max%22%2C%22chartLabel%22%3A%22Max%22%2C%22themeColor%22%3A%22infographicC%22%2C%22style%22%3A%7B%22strokeDasharray%22%3A%222+2%22%7D%7D%2C%7B%22id%22%3A%22std%22%2C%22label%22%3A%22St+Deviation%22%2C%22chartLabel%22%3A%22St+Deviation%22%2C%22themeColor%22%3A%22infographicD%22%7D%5D%7D%7D%5D&date=2019-08-24T05%3A00%3A00.000Z&selectedForEditing=true&aois=%5B%22ddjkLquzl%40dhcm%40lqg%7BAka%7B%7CAx%7Dre%40%22%2C%22bc0b2a%22%2Ctrue%5D&dateRange=2019-06-26T05%3A00%3A00.000Z%7C2019-09-22T05%3A00%3A00.000Z) shared by @Paridhi, the "delete all areas" button doesnot work unless we click on the polygon. I could find this behaviour only on this [link](https://staging.earth.gov/ghgcenter/exploration?datasets=%5B%7B%22id%22%3A%22post-wetland-id%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%2C%7B%22id%22%3A%22min%22%2C%22label%22%3A%22Min%22%2C%22chartLabel%22%3A%22Min%22%2C%22themeColor%22%3A%22infographicA%22%2C%22style%22%3A%7B%22strokeDasharray%22%3A%222+2%22%7D%7D%2C%7B%22id%22%3A%22max%22%2C%22label%22%3A%22Max%22%2C%22chartLabel%22%3A%22Max%22%2C%22themeColor%22%3A%22infographicC%22%2C%22style%22%3A%7B%22strokeDasharray%22%3A%222+2%22%7D%7D%2C%7B%22id%22%3A%22std%22%2C%22label%22%3A%22St+Deviation%22%2C%22chartLabel%22%3A%22St+Deviation%22%2C%22themeColor%22%3A%22infographicD%22%7D%5D%7D%7D%5D&date=2019-08-24T05%3A00%3A00.000Z&selectedForEditing=true&aois=%5B%22ddjkLquzl%40dhcm%40lqg%7BAka%7B%7CAx%7Dre%40%22%2C%22bc0b2a%22%2Ctrue%5D&dateRange=2019-06-26T05%3A00%3A00.000Z%7C2019-09-22T05%3A00%3A00.000Z), so might be something specific about that ploygon.

**Comment by sanzog03** [comment]
Note: I tried the link - with staging removed from the url, and the issue was there for the same polygon in production as well. So, not a bug that this release brought.

**Comment by slesaad** [comment]
cc @aboydnw

**Comment by aboydnw** [comment]
Somehow, in the link you provided, the dashboard thinks that an area is selected. You can see that in the URL parameter: &selectedForEditing=true

and you can see it in the UI:
![image](https://github.com/US-GHG-Center/veda-config-ghg/assets/92742765/1e7f4202-585b-4b88-86b9-799e5d6966ac)

I have tried to recreate this condition and have been unsuccessful. Any time I select, delete, create, or perform another action then the selected state seems to be correct. @sanzog03 or @paridhi-parajuli are either of you able to recreate this condition? That would lead us to the bug.

**Comment by aboydnw** [comment]
Ah, wait, as soon as I sent that I had a suspicion. See below

### Steps to Reproduce:
1. Go to exploration and analysis page
2. Create any number of AOIs
3. Select at least one of those AOIs
4. Copy the URL to send to somebody else
5. In a new window/tab, paste the URL
6. Notice that no AOIs are selected, although the URL and part of the UI believes that to be true (the highlighted part in my last comment)

### User Workaround:
- Clicking on any of the AOIs will select that AOI and "reset" the UI to function properly
- Clicking anywhere else on the map will unselect the AOIs and "reset" the UI to function properly

### Proposed Action
Since we know the workaround and the severity of the issue is not very high, I propose we place this ticket in the backlog, potentially for next PI.

**Comment by sanzog03** [comment]
@aboydnw We aren't exactly sure how we came to this bug, however, the steps to reproduce the bug seems like something we might have done. I agree that this is not a severe issue as there is a workaround to this, so placing it in the backlog seems good.
Also @paridhi-parajuli if you at some time remember how you came to this bug or be sure that these steps were what you did, update that in this ticket.

**Comment by aboydnw** [comment]
Related ticket: https://github.com/NASA-IMPACT/veda-ui/issues/950
