### ISSUE TITLE
Strategy for big changes for R3

### ISSUE THREAD

**Issue by slesaad** [US-GHG-Center/veda-config-ghg#474]
# Description

Some big changes are coming in for R3 that we've already started working on. However, these big changes are to be saved for the R3 release day rather than having them be part of the small releases we've been doing every 2 weeks.

We need to develop a convention for how we're going to make the big changes in parallel with our biweekly releases such that there are no big conflicts when we merge them in for the big release.

# AC
- [x] A guideline for how we manage big changes for R3

**Comment by slesaad** [comment]
Managing two different workflows, 1. preparing for a major milestone like R3 (where features are saved till the release date) while also performing 2. regular biweekly updates (releases) will follow the following strategy:

1. **Workflow for Regular Updates:** (our existing workflow)
   - Create feature branches for updates: `feature/bugfix-xyz`, `feature/update-abc`, etc. from `develop`.
   - Merge these small updates into the `develop` branch.
   - Test the `develop` branch thoroughly.
   - Once the tests pass, merge `develop` into `main` and tag it with the release version.

2. **Workflow for R3 Milestone:**
   - Create a dedicated branch for R3: `feature/R3`.
   - Branch out feature (for features to be saved for R3 release) branches from `feature/R3` to `feature/R3-xyz`.
   - Develop, test, and merge updates to `feature/R3` branch.
   - Regularly rebase or merge `develop` into `feature/R3` to keep it updated with the latest changes.
   - When R3 is ready, merge it to `develop` and test in staging.earth.gov/ghgcenter.
   - Once everything is validated, merge `develop` into `main` and tag it as R3 (v3.0.0).

This strategy ensures that the major milestone R3 can be developed independently without interrupting the regular biweekly updates, and both workflows are seamlessly integrated into the `main` branch when ready.

Does this sound like a good strategy @amarouane-ABDELHAK @anisbhsl @paridhi-parajuli @sanzog03 ?

**Comment by sanzog03** [comment]
Sounds like a perfect plan! @slesaad. Regularly rebasing/merging `develop` into `feature/R3` on every biweekly release would have manageable conflicts.
