### ISSUE TITLE
Header images for new dataset overview pages

### ISSUE THREAD

**Issue by slesaad** [US-GHG-Center/veda-config-ghg#512]
# Description
Header images with logo for the following datasets: (for overview pages)
- [ ] Vulcan
- [ ] GRA2PES
- [ ] NIST Urban Testbed

**Comment by rwyatt19** [comment]
In the [GRA2PES folder](https://drive.google.com/drive/folders/19B-wLUID02l_ckFUvA-95XifvweQerDM), I see no images in any of the docs. Should I just find a relevant stock photo?

**Comment by rwyatt19** [comment]
For the NIST Urban Testbed, I assume we need 3 banner images - one for each of the dataset landing pages (INFLUX, NEC, Los Angeles)?
